### ISSUE TITLE
xcframework対応の要望

### ISSUE THREAD

**Issue by ikesyo** [fan-ADN/nendSDK-iOS-pub#2]
SDK配布にxcframeworkが使われていないため、Appleシリコン搭載のMac上のiOSシミュレーター（arm64）向けにアプリをビルドすることができません。

参考: https://onesignal.com/blog/xcframeworks-guide/

**Comment by fan-t-kinami** [comment]
@ikesyo 
ご提案ありがとうございます。
現在 XCFramework 対応に関しては調査 検討を行なっている段階となります。

また、M1 Mac におけるアーキテクチャのエラーに関しては、
CocoaPodsを利用して nendSDK を組み込んでいただくか、
Build Settings の `Excluded Architecture` に `arm64` を設定することで回避可能と考えられます。
こちらもお試しいただけますでしょうか。

参考：
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io
